language: c
dist: trusty
sudo: true
services:
    - docker

env:
    - distribution: centos
    version: 7
    - distribution: fedora
    version: 27
    - distribution: fedora
    version: 26
    - distribution: ubuntu
    version: xenial
    - distribution: ubuntu
    version: trusty
    - distribution: debian
    version: stretch
    - distribution: debian
    version: jessie
  # - TEST_SUITE=deb_build
  # - TEST_SUITE=redhat_build
  # - TEST_SUITE=basic_build

before_install:
    - 'sudo docker pull ${distribution}:${version}'
    - 'sudo docker build --no-cache --rm --file=travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible travis'

script:
    'echo "HELLO "'
    # - 'container_id=$(mktemp)'
    # - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/nginx_role:ro ${distribution}-${version}:ansible > "${container_id}"'
    # - 'sudo docker exec "echo 'This is a test'"
